GET http://localhost:3001/api/admin/users

###

POST http://localhost:3001/api/admin/users
content-type: application/json

{
  "name": "gersom",
  "email": "gersomalaja@gmail.com",
  "password": "123456"
}